import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 19-Mar-2019 02:28:18 PM'
'File path: C:\\Users\\Brandon\\Documents\\Katalon Recorder Suites\\Lessons.html'
'Generated by: bolson@northwoodglobal.com'
'----------------------------------------------------'

String baseUrl = "https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html"

WebUI.openBrowser(baseUrl)

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"pause |  | 5000"
Thread.sleep("")

"open | https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html | "
selenium.open("https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html")

"store | YourAddress | youraddress"
String youraddress = "YourAddress"

"store | MyAddress | myaddress"
String myaddress = "MyAddress"

"click | id=email | "
selenium.click("id=email")

"type | id=email | myaddress"
selenium.type("id=email", myaddress)

"storeValue | id=email | emailtext"
String emailtext = selenium.getValue("id=email")

"echo | emailtext | "
System.out.println(emailtext)

"if | emailtext==youraddress | "
if (emailtext==youraddress){

"echo | YourAddress is in the Email field. | "
System.out.println("'YourAddress' is in the Email field.")

"elseIf | emailtext==myaddress | "
}else if (emailtext==myaddress){

"echo | My Address is in the Email field. | "
System.out.println("'My Address' is in the Email field.")

"else |  | "
}else{

"echo | Email field has a different value. | "
System.out.println("Email field has a different value.")
}
"endIf |  | "
"Method endIf is not found"

"store | 0 | w"
String w = "0"

"while | w&lt;2 | "
while (w<2){

"click | xpath=(//*[@id=infoForm]/div[11]/div/div[1]/label/input)[1] | "
selenium.click("xpath=(//*[@id='infoForm']/div[11]/div/div[1]/label/input)[1]")

"storeEval | w+1 | w"
String w = selenium.getEval(w + "+1")

"echo | Clicked on option # w | "
System.out.println("Clicked on option # " + w)}

"endWhile |  | "
"Method endWhile is not found"

"close | win_ser_local | "
selenium.close()

WebUI.closeBrowser()