import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 19-Mar-2019 02:28:11 PM'
'File path: C:\\Users\\Brandon\\Documents\\Katalon Recorder Suites\\Lessons.html'
'Generated by: bolson@northwoodglobal.com'
'----------------------------------------------------'

String baseUrl = "https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html"

WebUI.openBrowser(baseUrl)

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"pause |  | 5000"
Thread.sleep("")

"open | https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html | "
selenium.open("https://katalon-test.s3.amazonaws.com/demo-aut/dist/html/form.html")

"click | id=first-name | "
selenium.click("id=first-name")

"type | id=first-name | HELLO"
selenium.type("id=first-name", "HELLO")

"click | id=last-name | "
selenium.click("id=last-name")

"type | id=last-name | there"
selenium.type("id=last-name", "there")

"doubleClick | id=last-name | "
selenium.doubleClick("id=last-name")

"contextMenu | id=last-name | "
selenium.contextMenu("id=last-name")

"click | id=dob | "
selenium.click("id=dob")

"click | //th[2] | "
selenium.click("//th[2]")

"click | //div[2]/table/thead/tr[2]/th[3] | "
selenium.click("//div[2]/table/thead/tr[2]/th[3]")

"click | //span[3] | "
selenium.click("//span[3]")

"click | //tr[4]/td[6] | "
selenium.click("//tr[4]/td[6]")

"click | id=role | "
selenium.click("id=role")

"select | id=role | label=QA"
selenium.select("id=role", "label=QA")

"click | //select[@id='role']/option[2] | "
selenium.click("//select[@id='role']/option[2]")

"addSelection | id=expectation | label=High salary"
selenium.addSelection("id=expectation", "label=High salary")

"click | //select[@id='expectation']/option | "
selenium.click("//select[@id='expectation']/option")

"addSelection | id=expectation | label=Excellent colleagues"
selenium.addSelection("id=expectation", "label=Excellent colleagues")

"click | //select[@id='expectation']/option[3] | "
selenium.click("//select[@id='expectation']/option[3]")

"addSelection | id=expectation | label=Chance to go onsite"
selenium.addSelection("id=expectation", "label=Chance to go onsite")

"open | http://demo.guru99.com/test/ | "
selenium.open("http://demo.guru99.com/test/")

"click | name=bdaytime | "
selenium.click("name=bdaytime")

"type | name=bdaytime | 09/25/2019 02:45 PM"
selenium.type("name=bdaytime", "09/25/2019 02:45 PM")

"close | win_ser_local | "
selenium.close()

WebUI.closeBrowser()